repos:
  - repo: https://github.com/python-poetry/poetry
    rev: '1.3.1'  # add version here
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export

  - repo: local
    hooks:
      - id: dotenv-vault-build
        name: dotenv-vault build
        entry: npx dotenv-vault@latest build
        language: system
        stages: [pre-commit]


      #   args: ["-f", "requirements.txt", "--output", "requirements.txt", "--without-hashes"]
      # - id: poetry-export
      #   args: ["-f", "requirements.txt", "--output", "test-requirements.txt", "--only", "test", "--without-hashes"]