name: Post coverage comment

on:
  workflow_run:
    workflows: ["Run pytest"]
    types:
      - completed

jobs:
  test:
    name: Run tests & display coverage
    runs-on: ubuntu-latest
    if: github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success'
    steps:
    
      - name: Post comment
        uses: py-cov-action/python-coverage-comment-action@e5ccefa682f1d93b0ac3f0e85c88f2038787c8bb # v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_PR_RUN_ID: ${{ github.event.workflow_run.id }}
          VERBOSE: true